### ISSUE TITLE
article link

### ISSUE THREAD

**Issue by LHY0329** [hocop/Image-Reconstruction-using-Diffusion-Model#1]
Can you update the article link? Thank you

**Comment by hocop** [comment]
Hi!

I deleted my original article because it contained some wrong information. However, the code is valid.

Here is a paper that does basically the same: [GLIDE](https://openaccess.thecvf.com/content/CVPR2022/papers/Lugmayr_RePaint_Inpainting_Using_Denoising_Diffusion_Probabilistic_Models_CVPR_2022_paper.pdf).

I added a link to that paper as well as some results from my deleted article to the readme.
